### ISSUE TITLE
"Articles" => "Examples"

### ISSUE THREAD

**Issue by arokem** [sgraham9319/ForestPlotR#30]
Is it common to use the word "articles" to describe examples/vignettes? I would suggest replacing for clarity, but might be missing something.

**Comment by sgraham9319** [comment]
"Articles" is the default heading used by pkgdown to store vignettes. I guess there is a way to change this but it will likely be annoying and it seems that other package website often leave the default, so it probably won't confuse users too much. I will take a look into whether I can change this easily, but I'll not make any promises... Thanks!

**Comment by arokem** [comment]
If it's the default, it probably appears many other places, and is already well understood by anyone else showing up here. And there might be some principled reason that this is the default. You can just leave as-is, I think.
